name: ZAP Security Scan

on:
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: testing

      - name: Create ZAP Work Directory
        run: mkdir -p $GITHUB_WORKSPACE/zap/wrk

      - name: Adjust Permissions
        run: sudo chown -R $(whoami) $GITHUB_WORKSPACE/zap

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run python main.py
        run: nohup python main.py &
          
      # - name: Print Directory Structure
      #   run: ls -R $GITHUB_WORKSPACE

      # - name: ZAP Scan
      #   uses: zaproxy/action-baseline@v0.10.0
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
      #     target: 'http://${{ steps.get_host_ip.outputs.host_ip }}:5000'  # Adjust the port if needed
      #     #rules_file_name: '.zap/rules.tsv'
      #     cmd_options: '-a'
